# Generated by Django 3.0.2 on 2020-01-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateTimeField()),
                ('ticker', models.CharField(max_length=100)),
                ('stock_price', models.FloatField()),
                ('trend', models.CharField(max_length=200)),
                ('macd_trend', models.CharField(max_length=100)),
                ('money_flow_trend', models.CharField(max_length=100)),
                ('week_1', models.FloatField()),
                ('week_2', models.FloatField()),
                ('week_3', models.FloatField()),
                ('week_5', models.FloatField()),
                ('gap_1', models.FloatField()),
                ('gap_2', models.FloatField()),
                ('gap_3', models.FloatField()),
                ('earnings_call', models.DateTimeField()),
            ],
        ),
    ]
