# Generated by Django 3.0.2 on 2021-09-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='rsi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
