# Generated by Django 3.0.2 on 2020-01-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0003_remove_stockdata_stam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdata',
            name='trend',
        ),
        migrations.AddField(
            model_name='stockdata',
            name='stock_trend',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='earnings_call',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='gap_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='gap_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='gap_3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='macd_trend',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='money_flow_trend',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='week_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='week_2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='week_3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='week_5',
            field=models.FloatField(null=True),
        ),
    ]
