# Generated by Django 3.0.2 on 2020-01-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0006_stockdata_stock_displayed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='earnings_call_displayed',
            field=models.CharField(default='kaka', max_length=100),
            preserve_default=False,
        ),
    ]
