# Generated by Django 3.0.2 on 2020-01-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0007_stockdata_earnings_call_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='earnings_warning',
            field=models.CharField(default='kaka', max_length=100),
            preserve_default=False,
        ),
    ]
