# Generated by Django 3.0.2 on 2020-01-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0008_stockdata_earnings_warning'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='saved_to_history',
            field=models.BooleanField(default=False),
        ),
    ]
