# Generated by Django 3.0.2 on 2020-01-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0010_auto_20200119_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='dividends',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='profit',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='purchase_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='selling_price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='stocks_bought',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='stocks_sold',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='total_profit',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
