# Generated by Django 3.0.2 on 2020-01-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0011_auto_20200119_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='macd_clash',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='mfi_clash',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
