# Generated by Django 3.0.2 on 2020-01-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0012_auto_20200126_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='macd_color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='mfi_color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
    ]
