# Generated by Django 3.0.2 on 2020-01-27 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0017_auto_20200127_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
