# Generated by Django 3.0.2 on 2020-01-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ib_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockData',
            new_name='StockStreamingData',
        ),
    ]
