# Generated by Django 3.0.2 on 2020-02-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_api', '0002_auto_20200129_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=100)),
                ('stock_price', models.FloatField(null=True)),
                ('stock_high', models.FloatField(null=True)),
                ('stock_low', models.FloatField(null=True)),
                ('stock_close', models.FloatField(null=True)),
                ('stock_volume', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StockStreamingData',
        ),
    ]
