# Generated by Django 3.0.2 on 2020-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ib_api', '0003_auto_20200203_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='write_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
