# Generated by Django 3.0.2 on 2020-01-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='stam',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
