# Generated by Django 3.0.2 on 2020-01-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0004_auto_20200119_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='gap_1_color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='gap_2_color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='gap_3_color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='week_1_color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='week_2_color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='week_3_color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdata',
            name='week_5_color',
            field=models.CharField(default='green', max_length=100),
            preserve_default=False,
        ),
    ]
