# Generated by Django 3.0.2 on 2020-01-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0005_auto_20200119_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdata',
            name='stock_displayed_date',
            field=models.CharField(default='stam', max_length=100),
            preserve_default=False,
        ),
    ]
