# Generated by Django 3.0.2 on 2020-01-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0013_auto_20200126_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='macd_trend',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='money_flow_trend',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='stock_trend',
            field=models.FloatField(null=True),
        ),
    ]
