# Generated by Django 3.0.2 on 2020-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0015_stockdata_table_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='stock_date',
            field=models.DateField(),
        ),
    ]
