# Generated by Django 3.0.2 on 2020-01-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kadima', '0016_auto_20200127_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdata',
            name='stock_date',
            field=models.DateTimeField(),
        ),
    ]
